services:
  watchtower:
    image: containrrr/watchtower
    command:
      - '--label-enable'
      - '--interval'
      - '30'
      - '--rolling-restart'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
  reverse-proxy:
    image: traefik:v3.1
    command:
      - '--providers.docker'
      - '--providers.docker.exposedbydefault=false'
      - '--entryPoints.websecure.address=:443'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=admin@applogi.co'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  ui-bytes:
    image: ghcr.io/applogico/ui-bytes:latest
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.ui-bytes.rule=Host(`uibytes.dev`)'
      - 'traefik.http.routers.ui-bytes.entrypoints=websecure'
      - 'traefik.http.routers.ui-bytes.tls.certresolver=myresolver'
      - 'com.centurylinklabs.watchtower.enable=true'

    deploy:
      mode: replicated
      replicas: 3
    restart: always
volumes:
  letsencrypt:
